name: Build OpenRV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        qt-version: [5.15.2] # Specify the Qt versions you want to test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive' # This ensures that submodules are also cloned recursively

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Set up Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt-version }}
          host: linux
          target: desktop
          arch: gcc_64
          dir: ${{ runner.temp }}/Qt
          
      - name: Build OpenRV
        run: |
          mkdir build
          cd build
          cmake ..
          make
