name: Build OpenRV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive' # This ensures that submodules are also cloned recursively

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake qt5-default

      - name: Build OpenRV
        run: |
          mkdir build
          cd build
          cmake ..
          make
